#!/usr/bin/env python3
"""
Generate Lichess analysis Markdown files for the knowledge base.

Creates comprehensive documentation from Lichess computer analysis,
tactical patterns, and opening database insights.
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional


class LichessMarkdownGenerator:
    """Generate Markdown files with Lichess analysis insights."""

    def __init__(self, knowledge_dir: str = "knowledge"):
        """
        Initialize the Lichess markdown generator.

        Args:
            knowledge_dir: Directory to save markdown files
        """
        self.knowledge_dir = Path(knowledge_dir)
        self.knowledge_dir.mkdir(exist_ok=True)
        self.data_dir = Path("data")

    def generate_all(self, lichess_analysis: Dict = None, tactical_analysis: Dict = None,
                     opening_analysis: Dict = None, study_urls: List[str] = None):
        """
        Generate all Lichess analysis markdown files.

        Args:
            lichess_analysis: Computer analysis results
            tactical_analysis: Tactical pattern analysis
            opening_analysis: Opening repertoire analysis
            study_urls: List of Lichess study URLs
        """
        # Try to load from cache if not provided
        if not lichess_analysis:
            lichess_cache = self.data_dir / "lichess_analysis_cache.json"
            if lichess_cache.exists():
                with open(lichess_cache, 'r') as f:
                    cache_data = json.load(f)
                    lichess_analysis = cache_data.get("last_analysis")

        # Generate individual files
        if lichess_analysis:
            self.generate_accuracy_report(lichess_analysis)
            self.generate_mistake_analysis(lichess_analysis)

        if tactical_analysis:
            self.generate_tactical_patterns(tactical_analysis)

        if opening_analysis:
            self.generate_opening_recommendations(opening_analysis)

        if study_urls:
            self.generate_study_links(study_urls)

        # Generate combined improvement plan
        self.generate_improvement_plan(lichess_analysis, tactical_analysis, opening_analysis)

    def generate_accuracy_report(self, analysis: Dict):
        """Generate accuracy and performance report."""
        output_file = self.knowledge_dir / "lichess_accuracy.md"

        content = ["# Computer Analysis Report",
                   "",
                   f"*Generated by Lichess Analysis on {datetime.now().strftime('%B %d, %Y at %H:%M')}*",
                   "",
                   "## Performance Overview",
                   ""]

        # Overall statistics
        games_analyzed = analysis.get("games_analyzed", 0)
        avg_accuracy = analysis.get("average_accuracy", 0)
        avg_blunders = analysis.get("average_blunders_per_game", 0)
        avg_mistakes = analysis.get("average_mistakes_per_game", 0)
        avg_inaccuracies = analysis.get("average_inaccuracies_per_game", 0)

        content.extend([
            "### Summary Statistics",
            "",
            f"- **Games Analyzed:** {games_analyzed}",
            f"- **Average Accuracy:** {avg_accuracy}%",
            f"- **Average Blunders per Game:** {avg_blunders:.1f}",
            f"- **Average Mistakes per Game:** {avg_mistakes:.1f}",
            f"- **Average Inaccuracies per Game:** {avg_inaccuracies:.1f}",
            "",
            "### Performance Rating",
            ""
        ])

        # Performance rating based on accuracy
        if avg_accuracy >= 95:
            rating = "⭐⭐⭐⭐⭐ Exceptional"
            comment = "Your play is extremely accurate. Focus on maintaining consistency."
        elif avg_accuracy >= 90:
            rating = "⭐⭐⭐⭐ Excellent"
            comment = "Very strong play with minimal errors. Work on eliminating remaining mistakes."
        elif avg_accuracy >= 85:
            rating = "⭐⭐⭐ Good"
            comment = "Solid play with room for improvement. Focus on reducing blunders."
        elif avg_accuracy >= 80:
            rating = "⭐⭐ Average"
            comment = "Decent accuracy but significant errors. Study tactical patterns."
        else:
            rating = "⭐ Needs Improvement"
            comment = "Many inaccuracies affecting your games. Focus on calculation training."

        content.extend([
            f"**{rating}**",
            "",
            f"_{comment}_",
            "",
            "## Game-by-Game Analysis",
            ""
        ])

        # Individual game analysis
        games_analysis = analysis.get("games_analysis", [])[:10]  # Show top 10
        if games_analysis:
            content.append("| Date | Accuracy | Blunders | Mistakes | Inaccuracies |")
            content.append("|------|----------|----------|----------|--------------|")

            for game_data in games_analysis:
                game_analysis = game_data.get("analysis", {})
                date = game_data.get("date", "Unknown")[:10]  # Just the date part
                accuracy = game_analysis.get("accuracy", 0)
                blunders = len(game_analysis.get("blunders", []))
                mistakes = len(game_analysis.get("mistakes", []))
                inaccuracies = len(game_analysis.get("inaccuracies", []))

                content.append(f"| {date} | {accuracy}% | {blunders} | {mistakes} | {inaccuracies} |")

        content.extend([
            "",
            "## Accuracy Trends",
            "",
            "Track your accuracy improvement over time:",
            ""
        ])

        # Calculate trend (simplified)
        if games_analysis:
            recent_accuracy = sum(g["analysis"]["accuracy"] for g in games_analysis[:5]) / min(5, len(games_analysis))
            older_accuracy = sum(g["analysis"]["accuracy"] for g in games_analysis[5:10]) / max(1, len(games_analysis[5:10]))

            if recent_accuracy > older_accuracy + 2:
                trend = "📈 **Improving** - Your recent games show better accuracy"
            elif recent_accuracy < older_accuracy - 2:
                trend = "📉 **Declining** - Focus on maintaining concentration"
            else:
                trend = "➡️ **Stable** - Consistent performance"

            content.append(trend)

        # Write to file
        with open(output_file, 'w') as f:
            f.write("\n".join(content))

    def generate_mistake_analysis(self, analysis: Dict):
        """Generate detailed mistake analysis."""
        output_file = self.knowledge_dir / "lichess_mistakes.md"

        content = ["# Mistake Analysis",
                   "",
                   "*Critical positions and learning opportunities*",
                   "",
                   "## Most Common Mistakes",
                   ""]

        # Aggregate all mistakes
        all_blunders = []
        all_mistakes = []

        games_analysis = analysis.get("games_analysis", [])
        for game_data in games_analysis:
            game_analysis = game_data.get("analysis", {})
            all_blunders.extend(game_analysis.get("blunders", []))
            all_mistakes.extend(game_analysis.get("mistakes", []))

        # Categorize mistakes (simplified)
        mistake_categories = {
            "tactical": 0,
            "positional": 0,
            "endgame": 0,
            "opening": 0
        }

        for blunder in all_blunders:
            move_num = blunder.get("move_number", 0)
            if move_num <= 10:
                mistake_categories["opening"] += 1
            elif move_num >= 40:
                mistake_categories["endgame"] += 1
            else:
                # Simplified: assume high eval loss = tactical
                if blunder.get("eval_loss", 0) > 200:
                    mistake_categories["tactical"] += 1
                else:
                    mistake_categories["positional"] += 1

        content.extend([
            "### Mistake Categories",
            "",
            "| Category | Count | Percentage |",
            "|----------|-------|------------|"
        ])

        total_mistakes = sum(mistake_categories.values())
        if total_mistakes > 0:
            for category, count in sorted(mistake_categories.items(), key=lambda x: x[1], reverse=True):
                percentage = (count / total_mistakes * 100)
                content.append(f"| {category.capitalize()} | {count} | {percentage:.1f}% |")

        content.extend([
            "",
            "## Critical Blunders to Review",
            "",
            "These positions had the highest evaluation losses:",
            ""
        ])

        # Show worst blunders
        worst_blunders = sorted(all_blunders, key=lambda x: x.get("eval_loss", 0), reverse=True)[:5]
        for i, blunder in enumerate(worst_blunders, 1):
            content.extend([
                f"### Blunder #{i}",
                "",
                f"- **Move:** {blunder.get('move', 'Unknown')}",
                f"- **Move Number:** {blunder.get('move_number', 'Unknown')}",
                f"- **Evaluation Loss:** {blunder.get('eval_loss', 0)} centipawns",
                ""
            ])

        content.extend([
            "## Improvement Focus Areas",
            "",
            "Based on your mistake patterns, prioritize studying:",
            ""
        ])

        # Generate recommendations based on mistake patterns
        if mistake_categories["tactical"] > mistake_categories["positional"]:
            content.append("1. **Tactical Training**: Daily puzzles focusing on tactics")
        else:
            content.append("1. **Positional Understanding**: Study pawn structures and piece placement")

        if mistake_categories["opening"] > 5:
            content.append("2. **Opening Preparation**: Review opening principles and main lines")

        if mistake_categories["endgame"] > 5:
            content.append("3. **Endgame Technique**: Practice basic endgames")

        content.append("4. **Time Management**: Avoid time pressure situations")

        # Write to file
        with open(output_file, 'w') as f:
            f.write("\n".join(content))

    def generate_tactical_patterns(self, analysis: Dict):
        """Generate tactical patterns report."""
        output_file = self.knowledge_dir / "lichess_tactics.md"

        content = ["# Tactical Patterns Analysis",
                   "",
                   "*Recurring tactical themes in your games*",
                   "",
                   "## Pattern Statistics",
                   ""]

        pattern_stats = analysis.get("pattern_statistics", {})
        total_tactics = analysis.get("total_tactics_found", 0)
        games_analyzed = analysis.get("games_analyzed", 0)
        tactical_richness = analysis.get("tactical_richness", 0)

        content.extend([
            f"- **Total Tactical Patterns Found:** {total_tactics}",
            f"- **Games Analyzed:** {games_analyzed}",
            f"- **Average Tactics per Game:** {tactical_richness:.1f}",
            "",
            "## Most Common Patterns",
            "",
            "| Pattern Type | Occurrences | Games with Pattern | Frequency |",
            "|--------------|-------------|-------------------|-----------|"
        ])

        # Sort patterns by frequency
        for pattern, stats in sorted(pattern_stats.items(), key=lambda x: x[1]["total_occurrences"], reverse=True):
            content.append(
                f"| {pattern.replace('_', ' ').title()} | "
                f"{stats['total_occurrences']} | "
                f"{stats['games_with_pattern']} | "
                f"{stats['frequency_per_game']:.2f}/game |"
            )

        content.extend([
            "",
            "## Tactical Strengths",
            ""
        ])

        # Identify strengths
        strengths = [p for p, s in pattern_stats.items() if s["frequency_per_game"] > 0.5]
        if strengths:
            content.append("You frequently create these tactical opportunities:")
            for strength in strengths:
                content.append(f"- **{strength.replace('_', ' ').title()}**")
        else:
            content.append("_No dominant tactical patterns identified yet._")

        content.extend([
            "",
            "## Tactical Opportunities",
            "",
            "Patterns to practice and incorporate more:",
            ""
        ])

        # Identify underused patterns
        all_patterns = ["fork", "pin", "skewer", "discovered_attack", "double_attack", "sacrifice"]
        missing_patterns = [p for p in all_patterns if p not in pattern_stats or pattern_stats[p]["total_occurrences"] < 2]

        if missing_patterns:
            for pattern in missing_patterns:
                content.append(f"- **{pattern.replace('_', ' ').title()}** - Rarely used in your games")
        else:
            content.append("You're using a good variety of tactical patterns!")

        content.extend([
            "",
            "## Training Recommendations",
            "",
            "1. **Pattern Recognition**: Solve puzzles focusing on your weak patterns",
            "2. **Calculation**: Practice 3-5 move combinations",
            "3. **Visualization**: Work on seeing patterns before they appear",
            "4. **Time Management**: Don't rush in tactical positions"
        ])

        # Write to file
        with open(output_file, 'w') as f:
            f.write("\n".join(content))

    def generate_opening_recommendations(self, analysis: Dict):
        """Generate opening repertoire recommendations."""
        output_file = self.knowledge_dir / "lichess_openings.md"

        content = ["# Opening Repertoire Analysis",
                   "",
                   "*Based on Lichess Opening Database*",
                   "",
                   "## Current Repertoire Performance",
                   ""]

        opening_analysis = analysis.get("opening_analysis", [])
        repertoire_summary = analysis.get("repertoire_summary", {})

        # White repertoire
        content.extend([
            "### As White",
            "",
            "| Opening | Games | Your Win Rate | Expected Win Rate | Performance |",
            "|---------|-------|---------------|-------------------|-------------|"
        ])

        white_openings = [o for o in opening_analysis if o.get("color") == "white"]
        for opening in sorted(white_openings, key=lambda x: x["games"], reverse=True)[:5]:
            perf_diff = opening["performance_diff"]
            if perf_diff > 5:
                indicator = "✅"
            elif perf_diff < -5:
                indicator = "⚠️"
            else:
                indicator = "➡️"

            content.append(
                f"| {opening['opening']} | {opening['games']} | "
                f"{opening['player_win_rate']}% | {opening['expected_win_rate']}% | "
                f"{indicator} {perf_diff:+.1f}% |"
            )

        # Black repertoire
        content.extend([
            "",
            "### As Black",
            "",
            "| Opening | Games | Your Win Rate | Expected Win Rate | Performance |",
            "|---------|-------|---------------|-------------------|-------------|"
        ])

        black_openings = [o for o in opening_analysis if o.get("color") == "black"]
        for opening in sorted(black_openings, key=lambda x: x["games"], reverse=True)[:5]:
            perf_diff = opening["performance_diff"]
            if perf_diff > 5:
                indicator = "✅"
            elif perf_diff < -5:
                indicator = "⚠️"
            else:
                indicator = "➡️"

            content.append(
                f"| {opening['opening']} | {opening['games']} | "
                f"{opening['player_win_rate']}% | {opening['expected_win_rate']}% | "
                f"{indicator} {perf_diff:+.1f}% |"
            )

        content.extend([
            "",
            "## Opening Recommendations",
            ""
        ])

        recommendations = analysis.get("recommendations", [])
        if recommendations:
            content.append("### Priority Changes")
            content.append("")
            for i, rec in enumerate(recommendations[:3], 1):
                content.extend([
                    f"#### {i}. {rec.get('opening', 'Unknown')}",
                    "",
                    f"- **Priority:** {rec.get('priority', 'medium').upper()}",
                    f"- **Issue:** {rec.get('issue', 'No specific issue')}",
                    f"- **Suggestion:** {rec.get('suggestion', 'Continue current approach')}",
                    ""
                ])

        content.extend([
            "## Suggested New Openings",
            "",
            "Based on your rating and style, consider adding these to your repertoire:",
            "",
            "_Note: Run the analysis with Lichess token to get personalized suggestions._"
        ])

        # Write to file
        with open(output_file, 'w') as f:
            f.write("\n".join(content))

    def generate_study_links(self, study_urls: List[str]):
        """Generate file with Lichess study links."""
        output_file = self.knowledge_dir / "lichess_studies.md"

        content = ["# Lichess Studies",
                   "",
                   "*Interactive training materials created for your improvement*",
                   "",
                   "## Available Studies",
                   ""]

        if study_urls:
            for i, url in enumerate(study_urls, 1):
                study_type = "Opening Repertoire" if "opening" in url.lower() else "Improvement Plan"
                content.extend([
                    f"### {i}. {study_type}",
                    "",
                    f"🔗 [{url}]({url})",
                    ""
                ])

            content.extend([
                "## How to Use These Studies",
                "",
                "1. Click on the study link to open in Lichess",
                "2. Use the analysis board to explore variations",
                "3. Practice the positions against the computer",
                "4. Review regularly to reinforce patterns",
                ""
            ])
        else:
            content.append("_No studies created yet. Run analysis with Lichess token to generate studies._")

        # Write to file
        with open(output_file, 'w') as f:
            f.write("\n".join(content))

    def generate_improvement_plan(self, lichess_analysis: Dict = None,
                                 tactical_analysis: Dict = None,
                                 opening_analysis: Dict = None):
        """Generate comprehensive improvement plan."""
        output_file = self.knowledge_dir / "lichess_improvement.md"

        content = ["# Personalized Improvement Plan",
                   "",
                   f"*Generated on {datetime.now().strftime('%B %d, %Y')}*",
                   "",
                   "## Priority Areas",
                   ""]

        priorities = []

        # Analyze accuracy issues
        if lichess_analysis:
            avg_accuracy = lichess_analysis.get("average_accuracy", 100)
            avg_blunders = lichess_analysis.get("average_blunders_per_game", 0)

            if avg_accuracy < 85:
                priorities.append({
                    "area": "Calculation Accuracy",
                    "priority": "HIGH",
                    "issue": f"Average accuracy is {avg_accuracy}%",
                    "action": "Daily tactical puzzles, slower time controls"
                })

            if avg_blunders > 1:
                priorities.append({
                    "area": "Blunder Reduction",
                    "priority": "HIGH",
                    "issue": f"Averaging {avg_blunders:.1f} blunders per game",
                    "action": "Blunder check routine before each move"
                })

        # Analyze tactical patterns
        if tactical_analysis:
            tactical_richness = tactical_analysis.get("tactical_richness", 0)
            if tactical_richness < 2:
                priorities.append({
                    "area": "Tactical Awareness",
                    "priority": "MEDIUM",
                    "issue": "Low tactical pattern creation",
                    "action": "Study attacking games, practice combinations"
                })

        # Analyze openings
        if opening_analysis:
            weak_openings = [o for o in opening_analysis.get("opening_analysis", [])
                           if o.get("performance_diff", 0) < -10]
            if weak_openings:
                priorities.append({
                    "area": "Opening Preparation",
                    "priority": "MEDIUM",
                    "issue": f"{len(weak_openings)} underperforming openings",
                    "action": "Review main lines, prepare specific responses"
                })

        # Sort by priority
        priority_order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
        priorities.sort(key=lambda x: priority_order.get(x["priority"], 3))

        # Write priorities
        for i, priority in enumerate(priorities[:5], 1):
            content.extend([
                f"### {i}. {priority['area']} [{priority['priority']}]",
                "",
                f"**Issue:** {priority['issue']}",
                "",
                f"**Action:** {priority['action']}",
                ""
            ])

        content.extend([
            "## Weekly Training Schedule",
            "",
            "### Monday - Tactics Day",
            "- 30 minutes tactical puzzles",
            "- Focus on pattern recognition",
            "",
            "### Tuesday - Opening Study",
            "- Review one opening variation",
            "- Play practice games in that opening",
            "",
            "### Wednesday - Game Analysis",
            "- Analyze 1-2 recent games",
            "- Identify critical moments",
            "",
            "### Thursday - Endgame Practice",
            "- Study basic endgame positions",
            "- Practice against engine",
            "",
            "### Friday - Blitz Practice",
            "- Play with focus on avoiding blunders",
            "- Quick game review after each game",
            "",
            "### Weekend - Long Games",
            "- Play 1-2 longer time control games",
            "- Deep analysis with engine",
            "",
            "## Progress Tracking",
            "",
            "Track these metrics weekly:",
            "- [ ] Average game accuracy",
            "- [ ] Blunders per game",
            "- [ ] Opening win rates",
            "- [ ] Tactical puzzle rating",
            "- [ ] Number of games analyzed",
            "",
            "## Resources",
            "",
            "- **Lichess Studies**: See lichess_studies.md for your personalized studies",
            "- **Lichess Puzzles**: https://lichess.org/training",
            "- **Opening Explorer**: https://lichess.org/opening",
            "- **Analysis Board**: https://lichess.org/analysis"
        ])

        # Write to file
        with open(output_file, 'w') as f:
            f.write("\n".join(content))


def main():
    """Test the Lichess markdown generator."""
    generator = LichessMarkdownGenerator()

    # Generate sample files
    sample_lichess = {
        "games_analyzed": 10,
        "average_accuracy": 87.5,
        "average_blunders_per_game": 1.2,
        "average_mistakes_per_game": 2.3,
        "average_inaccuracies_per_game": 3.1
    }

    sample_tactical = {
        "total_tactics_found": 45,
        "games_analyzed": 20,
        "tactical_richness": 2.25,
        "pattern_statistics": {
            "fork": {"total_occurrences": 15, "games_with_pattern": 8, "frequency_per_game": 0.75},
            "pin": {"total_occurrences": 10, "games_with_pattern": 7, "frequency_per_game": 0.5},
            "check": {"total_occurrences": 20, "games_with_pattern": 12, "frequency_per_game": 1.0}
        }
    }

    generator.generate_all(sample_lichess, sample_tactical)
    print("Generated Lichess analysis markdown files")


if __name__ == "__main__":
    main()